### ISSUE TITLE
Companion crashes with Zoom Iso 2.2.0

### ISSUE THREAD

**Issue by mixmexmax** [bitfocus/companion-module-zoom-osc-iso#175] opened 2024-05-02 07:08 UTC
We are experiencing crashes of Companion together with the new version of Zoom Iso. Sometimes also Zoom Iso crashes and ends along with Companion. What we do is select a participant by index and then do an iso-output and iso-audio to one of 4 outputs. Selecting works fine, also with feedback, but when we assign the selected to the output it does the command correctly (so the selected Participant populöates the output in Zoom Iso), but then no other function works in Companion relation to the Zoom-Iso/OSC-module. We get this in the log over and over again: 

Instance/Wrapper/OSC___ISO1	debug	Child is not running, unable to send message: {"direction":"call","name":"variablesChanged","payload":"{\"variablesIds\":[\"internal:time_hms\",\"internal:time_s\",\"internal:time_unix\",\"internal:time_hms_12\"]}"}
02.05.2024 08:49	Instance/OSC___ISO1	verbose	"stdout: Starting up module class: u
"
02.05.2024 08:49	Instance/OSC___ISO1	verbose	"stdout: Sentry disabled
"
02.05.2024 08:49	Instance/OSC___ISO1	verbose	"stderr: Module registration failed Error: Call timed out
    at t.IpcWrapper.sendWithCb (C:\Program Files\Companion\resources\bundled-modules\zoom-osc-iso\main.js:2:911136)
    at C:\Program Files\Companion\resources\bundled-modules\zoom-osc-iso\main.js:2:904217
"
02.05.2024 08:49	Instance/Wrapper/OSC___ISO1	debug	Child is not running, unable to send message: {"direction":"call","name":"variablesChanged","payload":"{\"variablesIds\":[\"internal:time_hms\",\"internal:time_s\",\"internal:time_unix\",

Any suggestions? 

Using the latest beta as of 1.5.2024 with the 3.12 module of ZoomOSC. Also tried the current stable version that has the 3.11 module, same results. Tried different computers, Companion locally and from another machine etc etc....

**Comment by digitaldrummerj** [comment] 2024-05-02 08:30
The provided logs looks to be the Companion log.  Can you see if the module log has any errors in it?  One of the icons next to the connection on the connections tab will open up the module log.

**Comment by mixmexmax** [comment] 2024-05-02 09:54
Yes, this comes out of the module log: 
[module-log-2.5.2024-11_48_35.csv](https://github.com/bitfocus/companion-module-zoom-osc-iso/files/15186547/module-log-2.5.2024-11_48_35.csv)

**Comment by digitaldrummerj** [comment] 2024-05-02 17:08
@mixmexmax unfortunately the logs did not provide any useful data as to the cause of the crash.  I have a version of the module for you to try out in Pull Request #176 that hopefully will not crash the module but will instead output to the module log the data that it is trying to process when it is erroring.  Please give the updated module a try and send me the module log of the error message.

**Comment by mixmexmax** [comment] 2024-05-04 19:42
Here is the log I made with the forked version
[module-log-4.5.2024-21_28_45.csv](https://github.com/bitfocus/companion-module-zoom-osc-iso/files/15210796/module-log-4.5.2024-21_28_45.csv)

**Comment by digitaldrummerj** [comment] 2024-05-04 21:32
@mixmexmax can you try clearing the cache in ZoomOSC and see if that fixes it.  Can you also upload pictures of the output, audio, and settings tabs in ZoomISO?

**Comment by mixmexmax** [comment] 2024-05-05 13:07
Clearing the cache did not change the error in the module log. 
Yesterday I forgot to mention that with the 3.13 version of the module there are no crashes of the companion-module any more. The selection as well as the switching of video and audio-output seems to work multiple times without failing. What I also tried is use another Audio-device, that did not change anything either. I wanted to rule out that there is a problem with the special character in the name of the audio-device ("SSL2+"). But same thing with audio-device "Monitor" . 
Here are the requested screenshots: 
<img width="808" alt="Bildschirmfoto 2024-05-05 um 14 59 43" src="https://github.com/bitfocus/companion-module-zoom-osc-iso/assets/168710787/205874de-49a7-4260-ae19-5c8f492de423">
<img width="1169" alt="Bildschirmfoto 2024-05-05 um 15 00 11" src="https://github.com/bitfocus/companion-module-zoom-osc-iso/assets/168710787/1944b758-a737-4ea6-be5c-44b2897a9822">
<img width="1164" alt="Bildschirmfoto 2024-05-05 um 15 00 28" src="https://github.com/bitfocus/companion-module-zoom-osc-iso/assets/168710787/0a44331b-f85d-4817-8f25-7e58caee5c39">

**Comment by digitaldrummerj** [comment] 2024-06-03 00:33
closing at latest version is not having this issue

**Closed by digitaldrummerj** 2024-06-03 00:33 UTC
